server:
  port: 9000  # 网关通常占用 80/8080/9000

spring:
  application:
    name: megaticket-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service-route
          uri: lb://megaticket-service-user
          predicates:
            - Path=/api/v1/user/**
        - id: cinema-service-route
          uri: lb://megaticket-service-cinema
          predicates:
            - Path=/api/v1/cinema/**
        - id: seat-service-route
          uri: lb://megaticket-service-seat
          predicates:
            - Path=/api/v1/seat/**
        - id: order-service-route
          uri: lb://megaticket-service-order
          predicates:
            - Path=/api/v1/order/**
        - id: pay-service-route
          uri: lb://megaticket-service-pay
          predicates:
            - Path=/api/v1/pay/**

megaticket:
  jwt:
    secret: MegaticketSecretKeyMustBeVeryLongAndSecureEnoughForHS256
