megaticket:
  jwt:
    secret: MegaticketSecretKeyMustBeVeryLongAndSecureEnoughForHS256

spring:
  application:
    name: megaticket-service-cinema
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/megaticket
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:271224}
server:
  port: 8082
